eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8222
spring:
  config:
    import: configserver:http://localhost:8088
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: airline
          uri: http://localhost:9097  # airline service actual port
          predicates:
            - Path=/airline/**
        - id: flightservice
          uri: http://localhost:9098  # flightservice actual port
          predicates:
            - Path=/flights/**
        - id: passenger
          uri: http://localhost:9099  # passenger service actual port
          predicates:
            - Path=/passangerinfo/**
